### PR TITLE
First Task

### PR DESCRIPTION
**Pull request by hritikyadav07**
Completed the first task of adding
Signup page, Login Page, Main Page, Dashboard Page, Journal Page Now all left in them is to fine tune them .

### CODE REVIEW

**Comment by hritikyadav07** [comment]
image 
main page

**Comment by hritikyadav07** [comment]
image
login page 
signup page is also similar

**Comment by hritikyadav07** [comment]
image
image
 DashBoard Page

**Comment by hritikyadav07** [comment]
to access these pages 
add 
/login
/signup
/dashboard

on the link in the bar

**Comment by codernotme** [comment]
Merged

**Pull request merged**
